In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('pre-process_datasample_2.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
Country      11 non-null object
Age          11 non-null float64
Salary       11 non-null float64
Purchased    11 non-null object
dtypes: float64(2), object(2)
memory usage: 464.0+ bytes


In [4]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
data.describe()

Age        Salary
count  11.000000     11.000000
mean   40.909091  62434.272727
std    11.148583  12459.130019
min    27.000000  45000.000000
25%    34.500000  53000.000000
50%    38.000000  61000.000000
75%    46.000000  69888.500000
max    67.000000  83000.000000

In [11]:
#Delete the record where the label is missing
#drop() ----> Requires index
data.drop(data.index[data.Purchased.isna()] , inplace=True )


In [13]:
#Handle age column
#Mean 
data.Age.mean()

38.3

In [14]:
#fillna means replace NaN with the value assigned in the function
data.Age.fillna(data.Age.mean() , inplace=True)
data

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
5    France  35.0  58000.0       Yes
6     Spain  38.3  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10      NaN  34.0  45000.0       Yes

In [15]:
data.Salary.fillna(data.Salary.mean(), inplace=True)
data

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0  61900.0       Yes
5    France  35.0  58000.0       Yes
6     Spain  38.3  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10      NaN  34.0  45000.0       Yes

In [26]:
data.Country.mode()[0] #Ensurring the source and destination datatype is same

'France'

In [19]:
data.Country.unique()

array(['France', 'Spain', 'Germany', nan], dtype=object)

In [24]:
data.Country.fillna( data.Country.mode()[0] , inplace=True)
data

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0  61900.0       Yes
5    France  35.0  58000.0       Yes
6     Spain  38.3  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10   France  34.0  45000.0       Yes

In [35]:
#Dummy Variables in Pandas
#Handling Categorical Data
dummyDF = pd.get_dummies(data.Country)


In [36]:
remainingDF = data.iloc[:,1:]

In [38]:
data2 = pd.concat([ dummyDF , remainingDF ] , axis = 1)
data2

France  Germany  Spain   Age   Salary Purchased
0        1        0      0  44.0  72000.0        No
1        0        0      1  27.0  48000.0       Yes
2        0        1      0  30.0  54000.0        No
3        0        0      1  38.0  61000.0        No
4        0        1      0  40.0  61900.0       Yes
5        1        0      0  35.0  58000.0       Yes
6        0        0      1  38.3  52000.0        No
7        1        0      0  48.0  79000.0       Yes
8        0        1      0  50.0  83000.0        No
9        1        0      0  37.0  67000.0       Yes
10       1        0      0  34.0  45000.0       Yes

In [39]:
#Seperate your data as features and label
#Ensure the data is in numpy array
features = data2.iloc[:, :-1].values
label = data2.Purchased.values

In [41]:
features

array([[1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.70e+01, 4.80e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.00e+01, 5.40e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.19e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+01, 5.80e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.83e+01, 5.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.00e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.70e+01, 6.70e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.40e+01, 4.50e+04]])

In [42]:
label

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes',
       'Yes'], dtype=object)

In [ ]:
#If you are using sklearn for model creation,
# Your label can be numeric or categorical(string also)
#If you are working on Neural Networks (Deep Learning), Then handling label is compulsory
#Your label is number.

In [45]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
features = scale.fit_transform(features)
features

array([[ 1.09544512e+00, -6.12372436e-01, -6.12372436e-01,
         8.50479346e-01,  8.58949016e-01],
       [-9.12870929e-01, -6.12372436e-01,  1.63299316e+00,
        -1.68603800e+00, -1.18211795e+00],
       [-9.12870929e-01,  1.63299316e+00, -6.12372436e-01,
        -1.23841729e+00, -6.71851210e-01],
       [-9.12870929e-01, -6.12372436e-01,  1.63299316e+00,
        -4.47620709e-02, -7.65400113e-02],
       [-9.12870929e-01,  1.63299316e+00, -6.12372436e-01,
         2.53651735e-01,  0.00000000e+00],
       [ 1.09544512e+00, -6.12372436e-01, -6.12372436e-01,
        -4.92382779e-01, -3.31673382e-01],
       [-9.12870929e-01, -6.12372436e-01,  1.63299316e+00,
        -1.06017881e-15, -8.41940124e-01],
       [ 1.09544512e+00, -6.12372436e-01, -6.12372436e-01,
         1.44730696e+00,  1.45426021e+00],
       [-9.12870929e-01,  1.63299316e+00, -6.12372436e-01,
         1.74572076e+00,  1.79443804e+00],
       [ 1.09544512e+00, -6.12372436e-01, -6.12372436e-01,
        -1.93968974e-01

In [44]:
features

array([[1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.70e+01, 4.80e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.00e+01, 5.40e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.19e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+01, 5.80e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.83e+01, 5.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.00e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.70e+01, 6.70e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.40e+01, 4.50e+04]])

In [46]:
from sklearn.preprocessing import MinMaxScaler
scale2 = MinMaxScaler(feature_range=(0,1))
features = scale2.fit_transform(features)

In [47]:
?MinMaxScaler