In [1]:
#NUMPY - Numerical Python
# To create and work with Arrays
# 1 Dimensional Array (Scalar)
# 2 Dimensional Array (Vectors)
# n Dimensional Array

In [2]:
#Import the package
import numpy as np

In [3]:
oneDimArray = np.array([1,2,3,4,5])

In [4]:
oneDimArray

array([1, 2, 3, 4, 5])

In [5]:
oneDimArray.shape

(5,)

In [6]:
oneDimArray.ndim

1

In [7]:
twoDimensionalArray = np.array([[1,2],[3,4]])

In [8]:
twoDimensionalArray

array([[1, 2],
       [3, 4]])

In [9]:
twoDimensionalArray.shape

(2, 2)

In [10]:
twoDimensionalArray.ndim

2

In [11]:
#Array Addition - Elementwise operation
resultArray = twoDimensionalArray + twoDimensionalArray
resultArray

array([[2, 4],
       [6, 8]])

In [12]:
#Array Multiplication - Elementwise Operation
resultArray = twoDimensionalArray * twoDimensionalArray
resultArray

array([[ 1,  4],
       [ 9, 16]])

In [13]:
#Matrix Creation (Maths)
twoDimensionalMatrix = np.matrix([[1,2],[3,4]])

In [15]:
resultMatrix = twoDimensionalMatrix * twoDimensionalMatrix
resultMatrix

matrix([[ 7, 10],
        [15, 22]])

In [16]:
oneDimArray = np.array([1,2,3,4,5])
twoDimensionalArray = np.array([[1,2],[3,4]])

In [17]:
oneDimArray[2:4]

array([3, 4])

In [18]:
oneDimArray[2]

3

In [19]:
twoDimensionalArray[0]

array([1, 2])

In [20]:
twoDimensionalArray[1]

array([3, 4])

In [21]:
twoDimensionalArray[0,0]

1

In [22]:
#Pandas - Data Analysis Library
# Exploratory Data Analysis
# Statistical Analysis
# Understanding and Working with Data
# Data Prepartion

In [23]:
import pandas as pd

In [25]:
#DataFrame using Python List and DataFrame()
dataList = [[1,'Prashant',1000],[2,'Arun',2000]]
empData = pd.DataFrame(dataList , columns=['eid','ename','esal'])
empData

eid     ename  esal
0    1  Prashant  1000
1    2      Arun  2000

In [28]:
#Load data from file --- No header
employeeDF = pd.read_csv('employee.csv' , header=None , names=['eid','ename','esal'])
#employeeDF = pd.read_csv("E:\DataScienceSL\27JulyMLBatch\Day2\employee.csv")
employeeDF

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [31]:
emp2DF = pd.read_csv('employeeWithHeaders.csv', sep='\t')
emp2DF

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000

In [33]:
employeeDF

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [35]:
#To get the detailed documentation of given function
?pd.read_csv

In [36]:
employeeDF.head(3)

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000

In [37]:
#iloc -> index location
#iloc[rows,columns]
employeeDF.iloc[2:4 ,:] # : Consider everything

eid     ename  esal
2    3    Chitra  2000
3    4  Utkarsha  9878

In [38]:
employeeDF.iloc[[2,4] ,:] 

eid   ename  esal
2    3  Chitra  2000
4    5    Ajit  9999

In [40]:
employeeDF.iloc[:,[2]]

esal
0  1000
1  2000
2  2000
3  9878
4  9999

In [41]:
employeeDF

eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    4  Utkarsha  9878
4    5      Ajit  9999

In [43]:
#Extract those employee records whose salary is greater than 3000
employeeDF[employeeDF['esal'] > 3000]

eid     ename  esal
3    4  Utkarsha  9878
4    5      Ajit  9999