In [1]:
import tensorflow as tf

from tensorflow.keras import layers

#### Generating random values

In [2]:
zero_initializer = tf.zeros_initializer()

tensor_1 = zero_initializer(shape=(2, 3))

tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [3]:
random_normal_initializer = tf.random_normal_initializer()

tensor_2 = random_normal_initializer(shape=(4, 5))

tensor_2

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.0015359 , -0.00768777,  0.02052042, -0.01907   ,  0.042377  ],
       [ 0.0260491 ,  0.10835899,  0.05535808, -0.02334366, -0.02624059],
       [-0.04204807, -0.06617768,  0.00094021, -0.07507539, -0.05824383],
       [ 0.04488286,  0.05598111, -0.05822297, -0.01514271, -0.01171237]],
      dtype=float32)>

### Writing custom layer

##### Writing custom layer which implement  y=ax+b and return y as result

In [4]:
class SimpleLinear(layers.Layer):
    
    def __init__ (self, input_dim=16, units=8, **kwargs):
        super(SimpleLinear, self).__init__(**kwargs)
        
        w_init = tf.random_normal_initializer()
        
        self.w = tf.Variable(initial_value=w_init(shape=(input_dim, units), 
                                                  dtype='float32'), 
                             trainable=True)
        
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(initial_value=b_init(shape=(units),
                                                  dtype='float32'),
                             trainable=True)
    
    def call(self, input_tensor):
        
        return tf.matmul(input_tensor, self.w) + self.b

In [5]:
x = tf.ones((4, 3))

x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [6]:
layer1 = SimpleLinear(input_dim=3, units=5)

y = layer1(x)

print(y)

tf.Tensor(
[[-0.08927916 -0.13878676  0.10402076 -0.02676938  0.04600964]
 [-0.08927916 -0.13878676  0.10402076 -0.02676938  0.04600964]
 [-0.08927916 -0.13878676  0.10402076 -0.02676938  0.04600964]
 [-0.08927916 -0.13878676  0.10402076 -0.02676938  0.04600964]], shape=(4, 5), dtype=float32)


In [7]:
layer1.weights

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[-0.01986888, -0.06257363,  0.00108924,  0.02626933, -0.01911998],
        [ 0.00567439,  0.00283186,  0.09097283, -0.01630574,  0.0325064 ],
        [-0.07508468, -0.07904498,  0.01195868, -0.03673297,  0.03262321]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [8]:
layer1.w

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[-0.01986888, -0.06257363,  0.00108924,  0.02626933, -0.01911998],
       [ 0.00567439,  0.00283186,  0.09097283, -0.01630574,  0.0325064 ],
       [-0.07508468, -0.07904498,  0.01195868, -0.03673297,  0.03262321]],
      dtype=float32)>

In [9]:
layer1.b

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [10]:
layer1.trainable_variables

[<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
 array([[-0.01986888, -0.06257363,  0.00108924,  0.02626933, -0.01911998],
        [ 0.00567439,  0.00283186,  0.09097283, -0.01630574,  0.0325064 ],
        [-0.07508468, -0.07904498,  0.01195868, -0.03673297,  0.03262321]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>]

In [11]:
layer1.non_trainable_variables

[]

In [12]:
layer1.losses

[]

#### Using add_weight

In [13]:
class SimpleLinear(layers.Layer):
    
    def __init__(self, input_dim=16, units=8, **kwargs):
        
        super(SimpleLinear, self).__init__(**kwargs)
        
        self.w = self.add_weight(shape=(input_dim, units),
                                 initializer='ones',
                                 trainable=True)
        
        self.b = self.add_weight(shape=(units),
                                 initializer='ones',
                                 trainable=False)
        
    def call(self, input_tensor):
        return tf.matmul(input_tensor, self.w) + self.b

In [14]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 3))

print(x)

tf.Tensor(
[[-0.0342208   0.03750037  0.01079724]
 [-0.0273298   0.02210379  0.01500329]
 [ 0.02725191  0.0368872   0.00225583]
 [ 0.04407104 -0.04377061 -0.04793216]], shape=(4, 3), dtype=float32)


In [15]:
layer2 = SimpleLinear(input_dim=x.shape[1], units=4)

y = layer2(x)

print(y)

tf.Tensor(
[[1.0140768  1.0140768  1.0140768  1.0140768 ]
 [1.0097773  1.0097773  1.0097773  1.0097773 ]
 [1.0663949  1.0663949  1.0663949  1.0663949 ]
 [0.95236826 0.95236826 0.95236826 0.95236826]], shape=(4, 4), dtype=float32)


In [16]:
layer2.weights

[<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]

In [17]:
layer2.trainable_variables

[<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>]

In [18]:
layer2.non_trainable_variables

[<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]

In [19]:
class SimpleLinear(layers.Layer):
    
    def __init__(self, units=8, **kwargs):
        
        super(SimpleLinear, self).__init__(**kwargs)
        self.units = units

    def build(self, input_shape):
        
        self.w = self.add_weight(shape=(input_shape[-1], self.units),
                                 initializer='random_normal',
                                 trainable=True)
        
        self.b = self.add_weight(shape=(self.units),
                                 initializer='ones',
                                 trainable=True)
        
    def call(self, input_tensor):
        return tf.matmul(input_tensor, self.w) + self.b

In [20]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 5))

print(x)

tf.Tensor(
[[ 0.02467035 -0.01496311 -0.00960634 -0.04457356 -0.03302558]
 [-0.04899872  0.02599639  0.00155749 -0.04639119  0.02944628]
 [-0.01967686 -0.01039328  0.02680061 -0.04499957  0.01648284]
 [-0.00875422  0.01861483 -0.00118383 -0.00827408 -0.01909715]], shape=(4, 5), dtype=float32)


In [21]:
layer3 = SimpleLinear(units=3)

y = layer3(x)

print(y)

tf.Tensor(
[[0.9979495  1.0001174  0.99816567]
 [1.0029641  0.99669886 1.0004746 ]
 [1.0017658  0.99915856 0.9994459 ]
 [1.000316   1.0001205  0.9985429 ]], shape=(4, 3), dtype=float32)


In [22]:
layer3.losses

[]

In [23]:
class SimpleLinearBlock(layers.Layer):

    def __init__(self, block_1_units=2, block_2_units=4, block_3_units=8, **kwargs):
        super(SimpleLinearBlock, self).__init__(**kwargs)
        
        self.linear_1 = SimpleLinear(block_1_units)
        self.linear_2 = SimpleLinear(block_2_units)
        self.linear_3 = SimpleLinear(block_3_units)

    def call(self, inputs):

        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        
        x = self.linear_2(x)
        x = tf.nn.relu(x)
        
        return self.linear_3(x)

In [24]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 5))

print(x)

tf.Tensor(
[[-0.03946048 -0.03975517 -0.03787321 -0.03895148 -0.00758871]
 [-0.04922526 -0.04048183 -0.01923621  0.04303591  0.0163168 ]
 [-0.02420375 -0.01922588  0.03340223 -0.0114023  -0.04867698]
 [-0.03055423 -0.00682204  0.00107227  0.02042076 -0.04618406]], shape=(4, 5), dtype=float32)


In [25]:
simple_linear_block = SimpleLinearBlock()

y = simple_linear_block(x)

y

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[0.90212685, 1.0502387 , 0.9857854 , 0.91740775, 0.88879645,
        1.0305659 , 0.889248  , 1.0425507 ],
       [0.9021264 , 1.0502366 , 0.9857876 , 0.9174008 , 0.88878894,
        1.0305696 , 0.8892461 , 1.0425625 ],
       [0.9021285 , 1.0502363 , 0.9857748 , 0.9174034 , 0.8887758 ,
        1.0305704 , 0.88924724, 1.0425671 ],
       [0.90212697, 1.0502336 , 0.98578286, 0.9173933 , 0.88877153,
        1.0305747 , 0.88924426, 1.0425805 ]], dtype=float32)>

In [26]:
simple_linear_block.weights

[<tf.Variable 'simple_linear_block/simple_linear_3/Variable:0' shape=(5, 2) dtype=float32, numpy=
 array([[ 0.07589477, -0.10044587],
        [-0.00028782, -0.01916383],
        [-0.06368774,  0.0019035 ],
        [ 0.05298022, -0.01894481],
        [-0.03009824, -0.00583311]], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_3/Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_4/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.05691573,  0.02656799,  0.0064048 ,  0.02636926],
        [-0.03168918,  0.02296992, -0.09049986, -0.05119945]],
       dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_4/Variable:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_5/Variable:0' shape=(4, 8) dtype=float32, numpy=
 array([[-2.7213544e-02,  3.1473007e-02, -3.5119768e-02,  2.6942952e-02,
         -2.2789508e-0

In [27]:
simple_linear_block.trainable_weights

[<tf.Variable 'simple_linear_block/simple_linear_3/Variable:0' shape=(5, 2) dtype=float32, numpy=
 array([[ 0.07589477, -0.10044587],
        [-0.00028782, -0.01916383],
        [-0.06368774,  0.0019035 ],
        [ 0.05298022, -0.01894481],
        [-0.03009824, -0.00583311]], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_3/Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_4/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.05691573,  0.02656799,  0.0064048 ,  0.02636926],
        [-0.03168918,  0.02296992, -0.09049986, -0.05119945]],
       dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_4/Variable:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Variable 'simple_linear_block/simple_linear_5/Variable:0' shape=(4, 8) dtype=float32, numpy=
 array([[-2.7213544e-02,  3.1473007e-02, -3.5119768e-02,  2.6942952e-02,
         -2.2789508e-0

In [28]:
class RegularizationLoss(layers.Layer):

    def __init__(self, rate=1e-3, **kwargs):
        super(RegularizationLoss, self).__init__(**kwargs)
        
        self.rate = rate

    def call(self, input_tensor):
        self.add_loss(self.rate * tf.reduce_sum(input_tensor))
        
        return input_tensor

In [29]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 5))

print(x)

tf.Tensor(
[[ 0.03730351  0.04356767  0.02137389  0.02603621  0.02190751]
 [ 0.00549287 -0.00827659 -0.01739709 -0.02873032 -0.01587219]
 [ 0.04945782  0.04769165 -0.01532748 -0.01396229  0.04666144]
 [-0.01732673  0.03400924  0.02816853  0.03483668 -0.04273689]], shape=(4, 5), dtype=float32)


In [30]:
reg_loss_layer = RegularizationLoss()

y = reg_loss_layer(x)

y

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.03730351,  0.04356767,  0.02137389,  0.02603621,  0.02190751],
       [ 0.00549287, -0.00827659, -0.01739709, -0.02873032, -0.01587219],
       [ 0.04945782,  0.04769165, -0.01532748, -0.01396229,  0.04666144],
       [-0.01732673,  0.03400924,  0.02816853,  0.03483668, -0.04273689]],
      dtype=float32)>

In [31]:
reg_loss_layer.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.00023687746>]

In [32]:
class SimpleLinearRegularized(layers.Layer):
    
    def __init__(self, units=8, **kwargs):
        super(SimpleLinearRegularized, self).__init__(**kwargs)
        
        self.units = units
        self.reg = RegularizationLoss(1e-2)

    def build(self, input_shape):
        
        self.w = self.add_weight(shape=(input_shape[-1], self.units),
                                 initializer='random_normal',
                                 trainable=True)
        
        self.b = self.add_weight(shape=(self.units),
                                 initializer='ones',
                                 trainable=True)
        
    def call(self, input_tensor):
        
        output = tf.matmul(input_tensor, self.w) + self.b
        
        return self.reg(output)

In [33]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 5))

print(x)

tf.Tensor(
[[-0.00743013 -0.0001335  -0.02866185  0.02778459 -0.0288618 ]
 [-0.04805789  0.04186578  0.03177341 -0.02208978 -0.01787059]
 [-0.04887817 -0.0467484  -0.04797031  0.02621657 -0.03095305]
 [ 0.00220103  0.01176266 -0.00769063 -0.04209554 -0.01088507]], shape=(4, 5), dtype=float32)


In [34]:
layer4 = SimpleLinearRegularized(units=3)

y = layer4(x)

print(y)

tf.Tensor(
[[0.9978588  1.0012716  0.99876904]
 [1.00071    0.9972389  1.0031072 ]
 [0.99884844 1.0037364  0.994497  ]
 [1.0017674  0.9992873  1.0021176 ]], shape=(4, 3), dtype=float32)


In [35]:
tf.matmul(x, layer4.w) + layer4.b

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.9978588 , 1.0012716 , 0.99876904],
       [1.00071   , 0.9972389 , 1.0031072 ],
       [0.99884844, 1.0037364 , 0.994497  ],
       [1.0017674 , 0.9992873 , 1.0021176 ]], dtype=float32)>

In [36]:
layer4.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.11999209>]

In [37]:
class DenseRegularized(layers.Layer):
    
    def __init__(self, units=8, **kwargs):
        super(DenseRegularized, self).__init__(**kwargs)
        
        self.dense = layers.Dense(units, kernel_regularizer=tf.keras.regularizers.l2(1e-3))

        self.reg = RegularizationLoss(1e-2)

    def call(self, input_tensor):
        
        return self.reg(self.dense(input_tensor))

In [38]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 5))

print(x)

tf.Tensor(
[[ 0.04129548  0.03124814  0.0085     -0.01742555  0.01846952]
 [-0.03748672  0.02428729 -0.02671628  0.01622481  0.04348439]
 [ 0.04368139 -0.01148559 -0.04284557  0.00981519  0.02600468]
 [ 0.02071592 -0.02317998  0.02401484 -0.01383345 -0.04121181]], shape=(4, 5), dtype=float32)


In [39]:
layer5 = DenseRegularized(units=3)

y = layer5(x)

print(y)

tf.Tensor(
[[ 0.01330353  0.00016853 -0.05173451]
 [ 0.00745268  0.0102701   0.02861171]
 [ 0.06117264  0.00524457 -0.04640967]
 [-0.01233857 -0.01025378 -0.01344557]], shape=(4, 3), dtype=float32)


In [40]:
layer5.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.0032079217>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-7.958338e-05>]

In [41]:
class SimpleLinear(layers.Layer):
    
    def __init__(self, units=8, **kwargs):
        
        super(SimpleLinear, self).__init__(**kwargs)
        self.units = units

    def build(self, input_shape):
        
        self.w = self.add_weight(shape=(input_shape[-1], self.units),
                                 initializer='random_normal',
                                 trainable=True)
        
        self.b = self.add_weight(shape=(self.units),
                                 initializer='ones',
                                 trainable=True)
        
    def call(self, input_tensor):
        return tf.matmul(input_tensor, self.w) + self.b
    
    def get_config(self):
        
        config = super(SimpleLinear, self).get_config()
        config.update({'units': self.units})
        
        return config

In [42]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 5))

print(x)

tf.Tensor(
[[-1.8779492e-02 -2.8716469e-02  1.1884153e-02 -4.1013967e-02
  -2.7351975e-03]
 [ 2.7448390e-02  1.3123825e-04  5.3234585e-03 -1.5205525e-02
  -4.0112279e-02]
 [-1.7390475e-03  8.2683451e-03  1.5293930e-02 -1.4508069e-02
   5.8886632e-03]
 [ 3.3531319e-02 -7.8979246e-03  5.9265718e-03  2.8960109e-03
  -4.3381006e-05]], shape=(4, 5), dtype=float32)


In [43]:
layer6 = SimpleLinear(units=3)

y = layer6(x)

print(y)

tf.Tensor(
[[1.0049342  1.0018066  1.0039151 ]
 [1.000288   1.0034908  0.99929273]
 [1.0019583  0.99917114 1.0019743 ]
 [0.99948907 1.0012959  0.9990688 ]], shape=(4, 3), dtype=float32)


In [44]:
config = layer6.get_config()

config

{'name': 'simple_linear_6', 'trainable': True, 'dtype': 'float32', 'units': 3}

In [45]:
new_layer6 = SimpleLinear.from_config(config)

new_layer6

In [46]:
new_layer6.units

3

In [47]:
class CustomDropout(layers.Layer):

    def __init__(self, rate, **kwargs):
        super(CustomDropout, self).__init__(**kwargs)
        self.rate = rate

    def call(self, inputs, training=None):
        if training:
            return tf.nn.dropout(inputs, rate=self.rate)
        
        return inputs

In [48]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 5))

print(x)

tf.Tensor(
[[-0.02028464  0.03477539 -0.00211916  0.0117229  -0.04656542]
 [ 0.04819066 -0.02938647  0.04836475  0.01913043  0.01871919]
 [-0.00780734  0.01585498 -0.02570226  0.03288959 -0.00688702]
 [-0.04253148  0.00299776  0.01585868  0.04945407  0.04794503]], shape=(4, 5), dtype=float32)


In [49]:
layer7 = CustomDropout(rate=0.4)

y = layer7(x)

print(y)

tf.Tensor(
[[-0.02028464  0.03477539 -0.00211916  0.0117229  -0.04656542]
 [ 0.04819066 -0.02938647  0.04836475  0.01913043  0.01871919]
 [-0.00780734  0.01585498 -0.02570226  0.03288959 -0.00688702]
 [-0.04253148  0.00299776  0.01585868  0.04945407  0.04794503]], shape=(4, 5), dtype=float32)


In [50]:
layer7 = CustomDropout(rate=0.4)

y = layer7(x, training=True)

print(y)

tf.Tensor(
[[-0.          0.05795898 -0.00353194  0.01953817 -0.07760904]
 [ 0.08031777 -0.04897746  0.08060791  0.03188406  0.        ]
 [-0.01301223  0.         -0.0428371   0.         -0.        ]
 [-0.          0.          0.02643114  0.          0.07990838]], shape=(4, 5), dtype=float32)


### Write custom model

`Writing very simple regression model`
##### By using `tf.keras.Sequential` we build model as below:

In [51]:
class CustomRegressionModel(tf.keras.Model):
    
    def __init__(self, input_shape, units_1=16, units_2=8, \
                 activation='relu', initializer='random_normal'):
        
        super(CustomRegressionModel, self).__init__()

        self.dense1 = layers.Dense(units_1,
                                   activation=activation,
                                   kernel_initializer=initializer,
                                   input_shape=[input_shape])
        
        self.dense2 = layers.Dense(units_2, 
                                   activation=activation, 
                                   kernel_initializer=initializer)
        
        self.dense3 = layers.Dense(1)
        
    def call(self, input_tensor):
        
        x = self.dense1(input_tensor)
        x = self.dense2(x)

        result = self.dense3(x)
        
        return result

In [52]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 8))

print(x)

tf.Tensor(
[[ 0.02010873 -0.01104734 -0.01837956 -0.00793121  0.02897124 -0.03248604
   0.03516323 -0.02263709]
 [-0.0014411   0.0149872   0.03537598 -0.03795952 -0.00665673  0.01459711
  -0.02898003  0.00366372]
 [-0.03015646 -0.03815961  0.03759431  0.01311399 -0.02519397  0.04282064
  -0.03242748  0.03252396]
 [-0.03943811  0.03025761 -0.04605551 -0.01691505 -0.03413906  0.0452756
  -0.02023634  0.02213   ]], shape=(4, 8), dtype=float32)


In [53]:
custom_reg_model = CustomRegressionModel(4, 8, x.shape[-1])

custom_reg_model.layers

#### After writing building the model

In [54]:
custom_reg_model(x)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[6.0793784e-05],
       [4.1060601e-04],
       [2.3572234e-04],
       [4.1273003e-04]], dtype=float32)>

In [55]:
custom_reg_model.summary()

Model: "custom_regression_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              multiple                  72        
_________________________________________________________________
dense_2 (Dense)              multiple                  72        
_________________________________________________________________
dense_3 (Dense)              multiple                  9         
Total params: 153
Trainable params: 153
Non-trainable params: 0
_________________________________________________________________


In [56]:
custom_reg_model = CustomRegressionModel(8, 16, x.shape[-1], 'sigmoid', 'zeros')

custom_reg_model.layers

In [57]:
custom_reg_model(x)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-1.0135751],
       [-1.0135751],
       [-1.0135751],
       [-1.0135751]], dtype=float32)>

In [58]:
custom_reg_model.summary()

Model: "custom_regression_model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              multiple                  144       
_________________________________________________________________
dense_5 (Dense)              multiple                  136       
_________________________________________________________________
dense_6 (Dense)              multiple                  9         
Total params: 289
Trainable params: 289
Non-trainable params: 0
_________________________________________________________________


In [59]:
class CustomRegressionModel(tf.keras.Model):
    
    def __init__(self, input_shape, layer_units=[8, 4], \
                 activation='relu', initializer='random_normal'):
        
        super(CustomRegressionModel, self).__init__()
        
        assert len(layer_units) > 0

        self.input_layer = layers.Dense(layer_units[0],
                                  activation=activation,
                                  kernel_initializer=initializer,
                                  input_shape=[input_shape])
        
        self.hidden_layers = []
        
        for i in range(1, len(layer_units)):
            self.hidden_layers.append(layers.Dense(layer_units[i],
                                                   activation=activation, 
                                                   kernel_initializer=initializer))

        self.output_layer = layers.Dense(1)
        
    def call(self, input_tensor):
        
        x = self.input_layer(input_tensor)
                               
        for layer in self.hidden_layers:
            x = layer(x)

        result = self.output_layer(x)
        
        return result

In [60]:
random_uniform_initializer = tf.random_uniform_initializer()
x = random_uniform_initializer(shape=(4, 8))

print(x)

tf.Tensor(
[[-0.0232506  -0.02581742  0.03840462 -0.04570484 -0.04016171  0.01851902
  -0.0261435   0.01902728]
 [ 0.00258154  0.00282932 -0.04577757 -0.00910568  0.02062101  0.00329734
   0.01817164 -0.04838033]
 [-0.0377516   0.01313509  0.03561752  0.02487304 -0.01783512 -0.00069733
  -0.00338119  0.02852054]
 [ 0.0220101  -0.01267161  0.01586124 -0.02015481 -0.04082725  0.00957469
  -0.04302105  0.00599651]], shape=(4, 8), dtype=float32)


In [61]:
custom_reg_model = CustomRegressionModel(x.shape[-1], [8, 16, 32], 'sigmoid')

custom_reg_model.layers

In [62]:
custom_reg_model(x)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.8483326 ],
       [-0.84833664],
       [-0.84833556],
       [-0.8483347 ]], dtype=float32)>

In [63]:
custom_reg_model.summary()

Model: "custom_regression_model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              multiple                  72        
_________________________________________________________________
dense_8 (Dense)              multiple                  144       
_________________________________________________________________
dense_9 (Dense)              multiple                  544       
_________________________________________________________________
dense_10 (Dense)             multiple                  33        
Total params: 793
Trainable params: 793
Non-trainable params: 0
_________________________________________________________________
