In [10]:
import numpy as np
import pandas as pd

In [11]:
data = pd.read_csv('pre-process_datasample.csv')

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      9 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [29]:
#Write code to deal with Missing data in  Country Columnn using Pandas
data['Country'].fillna(data.Country.mode()[0],inplace=True)
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [30]:
#Sklearn Expects your data to be in the form of Numpy Array
# .values convert DataFrame into Numpy Array
dataArray = data.values
dataArray

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['France', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [31]:
#Sklearn is a stubborn package
#I always expect my data to be numeric, categorical
#Deal with missing values
#Defect - Imputer class only accept numeric columns
#To deal with Categorical Column ---use pandas !!! :)
from sklearn.preprocessing import Imputer
#Object for Numerical Columns - Age, Salary
imputeForNumericColumn = Imputer(missing_values='NaN',
                strategy='mean',
                axis=0)


In [32]:
#Handle Numerical Missing Value Columns
#fit_transform ---> Calculate the mean and replace NaN with mean for respective column

dataArray[:,[1,2]] = imputeForNumericColumn.fit_transform(dataArray[:,[1,2]])
dataArray

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 63777.77777777778, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.77777777777778, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['France', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [35]:
#Deal with Categorical Data
# Country

from sklearn.preprocessing import LabelEncoder #To encode label values
from sklearn.preprocessing import OneHotEncoder #To create dummy variable from label column

encoderCountry = LabelEncoder()
dataArray[:,0] = encoderCountry.fit_transform(dataArray[:,0])


dataArray

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [0, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [40]:
encoderPurchased = LabelEncoder()
dataArray[:,3] = encoderPurchased.fit_transform(dataArray[:,3])
dataArray

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [0, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [42]:
encoderPurchased.classes_

array(['No', 'Yes'], dtype=object)

In [36]:
encoderCountry.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [41]:
#Taking care of Two categorical columns
oheCountry = OneHotEncoder(categorical_features=[0,3])
dataArray = oheCountry.fit_transform(dataArray).toarray()
dataArray

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 4