In [57]:
import numpy as np

In [58]:
list=[1,2,3,4]

arr = np.array(list)

In [59]:
arr

array([1, 2, 3, 4])

In [60]:
#2d Array
matrix=[[1,2,3],[4,5,6],[7,8,9]]

matrixArr=np.array(matrix)

In [61]:
matrixArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
#arrange function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [64]:
#zeros 
np.zeros(3)

array([0., 0., 0.])

In [65]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
#Ones Array
np.ones(3)

array([1., 1., 1.])

In [67]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
#linspace -> Evely spaced Array

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [69]:

np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [70]:
#Identity Matrix ->2d Squre Matrix with diagonal 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
#random number

np.random.rand(10)

array([0.23822091, 0.68384969, 0.60681346, 0.23079224, 0.57980608,
       0.72004419, 0.15552633, 0.90455819, 0.57320941, 0.98980655])

In [72]:
# random number standard normal distribution

np.random.randn(10)

array([ 0.00292502,  0.97313147,  0.1765672 , -0.2748795 ,  0.30027077,
       -1.84893507, -0.03501457,  0.22351133, -0.91845593, -1.60231585])

In [73]:
np.random.randn(5,5)

array([[-1.79412759, -0.35758892, -0.4664644 ,  0.45839271,  0.39564204],
       [ 0.36623137, -0.86364646, -0.35919604, -1.35076596, -0.61533016],
       [ 0.12633173, -2.73314282, -1.32849701,  0.45375803,  0.0893539 ],
       [-0.9766171 , -1.50129126, -0.758946  ,  0.32534168, -1.34632178],
       [-0.49721907,  0.26433242, -1.40868202,  0.14921574,  0.44974055]])

In [74]:
# 5 random integer between 1->100
np.random.randint(1,100,5)

array([ 8, 59,  5, 77, 59])

In [75]:
#creating random matrixx

randarr = np.random.randint(1,100,25)
randarr

array([ 2, 36, 82, 48, 25,  9, 66, 51, 31, 91,  9, 94, 29, 65, 17, 21, 79,
        1, 71, 13, 98, 82, 99, 11, 86])

In [76]:
randarr.reshape(5,5)

array([[ 2, 36, 82, 48, 25],
       [ 9, 66, 51, 31, 91],
       [ 9, 94, 29, 65, 17],
       [21, 79,  1, 71, 13],
       [98, 82, 99, 11, 86]])

In [77]:
#max value
randarr.max()

99

In [78]:
randarr.min()

1

In [79]:
#Index Location of Maximun value
randarr.argmax()

22

In [80]:
from numpy.random import randint

In [81]:
randint(2,10)

8

In [82]:
#slicing

arr =np.arange(0,11)

In [83]:
arr[1:5]

array([1, 2, 3, 4])

In [84]:
#Everything till index 5
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [85]:
#everyting till index 6 to last
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr2d[1,2]

6

In [88]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [89]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
boolArray=arr>5
boolArray

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [92]:
arr[boolArray]

array([ 6,  7,  8,  9, 10])

In [93]:
#
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [94]:
arr[arr<5]

array([1, 2, 3, 4])

In [95]:
#2d random Array
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [96]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr+arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [98]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [99]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [102]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [108]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [110]:
np.max(arr)

10

In [112]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [114]:
np.log(arr)

<ipython-input-114-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [125]:
matrix2d=np.linspace(1,25,25).reshape(5,5)

In [127]:
matrix2d.sum()

325.0

In [129]:
matrix2d.std()

7.211102550927978

In [130]:
#get sum of the column
matrix2d.sum(axis=0)

array([55., 60., 65., 70., 75.])