In [11]:
import numpy as np
import pandas as pd

In [12]:
startupData = pd.read_csv('50_Startups.csv')

In [13]:
#Checking if there exists any missing value
#Check the datatype of each column
startupData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     50 non-null float64
Marketing Spend    50 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [14]:
startupData.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [15]:
startupData.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [16]:
#Seperate the data as features and label
#Regression -- Sklearn expects your data (feature and label to be two dimensional)
features = startupData.iloc[:,[0,1,2,3]].values
label = startupData.iloc[:,[4]].values

In [17]:
#Handle Categorical Data
#Sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
countryLabel = LabelEncoder()
features[:,3] = countryLabel.fit_transform(features[:,3])


In [18]:
countryLabel.classes_

array(['California', 'Florida', 'New York'], dtype=object)

In [39]:
countryLabel.transform(np.array([['New York']]))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2], dtype=int64)

In [20]:
countryOHE = OneHotEncoder(categorical_features=[3])
features = countryOHE.fit_transform(features).toarray()
features

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [25]:
#lets check the best score possible
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
for i in range(1,51):
    X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=i)
    model = LinearRegression()
    model.fit(X_train,y_train)
    
    train_score=model.score(X_train,y_train)
    test_score=model.score(X_test,y_test)
    
    if test_score > train_score:
        print("Testing: {} Training: {} Seed: {}".format(test_score,train_score,i))

Testing: 0.9649618042060633 Training: 0.9424465426893971 Seed: 1
Testing: 0.9783259006626557 Training: 0.9398417195515446 Seed: 2
Testing: 0.9560357304860589 Training: 0.9473848999820091 Seed: 4
Testing: 0.9669763022158512 Training: 0.9438505226429931 Seed: 5
Testing: 0.990110511339781 Training: 0.9385918220043519 Seed: 10
Testing: 0.9726607102793833 Training: 0.9411603359254431 Seed: 14
Testing: 0.9633877651310018 Training: 0.946138584319559 Seed: 21
Testing: 0.9757906394981196 Training: 0.9425908513252554 Seed: 22
Testing: 0.9687727807395822 Training: 0.9464972114069966 Seed: 24
Testing: 0.9602561948870648 Training: 0.9454518446256155 Seed: 26
Testing: 0.9500997612784656 Training: 0.9482961316721963 Seed: 29
Testing: 0.9539450076684144 Training: 0.9435367947390881 Seed: 31
Testing: 0.9649795500576662 Training: 0.9343066184022641 Seed: 34
Testing: 0.9571971950121637 Training: 0.9477948990925947 Seed: 38
Testing: 0.9683573757861111 Training: 0.9390982119875836 Seed: 39
Testing: 0.95247

In [26]:
#Create train test split 80-20 rule
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=10)


In [27]:
#Create the model(Training the model)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train) #Create the equation

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [28]:
#Check the quality of the model
#1. Check whether the model is generalized or not
#2. Check whether the score is satisfactory for approval

#If the testscore > train score then we conclude the model is generalized
print("Training Score: ",model.score(X_train,y_train))
print("Testing Score: ",model.score(X_test,y_test))

Training Score:  0.9385918220043519
Testing Score:  0.990110511339781


In [36]:
#Testing model for prediction
#User input
#Features: R&DSpend,Admin,Mark,State
rdSpend= float(input("Enter R&D Spend: "))
admin = float(input("Enter Admin Spend: "))
markg = float(input("Enter Marketing Spend: "))
state = input("Enter State: ")

if state in countryLabel.classes_:
    #Feature before Dummy Varible
    featureBeforeDV = np.array([[rdSpend,admin,markg,state]])
    #Feature with DummyVariable
    featureBeforeDV[:,3] = countryLabel.transform(featureBeforeDV[:,3])
    featureBeforeDV = countryOHE.transform(featureBeforeDV).toarray()
    #Prediction
    print("Profit Expected is {}".format(model.predict(featureBeforeDV)))
else:
    print("Model don't know about {}".format(state))

Enter R&D Spend: 23456
Enter Admin Spend: 2345
Enter Marketing Spend: 123456
Enter State: california
Model don't know about california


In [37]:
# We realized we need to deploy model,countryLabel and countryOHE
# Lets start the deployment process
import pickle
#Deploy model
pickle.dump(model,open('ProfitPredictor.model','wb'))
#Deploy Label Encoder object
pickle.dump(countryLabel,open('CountryEncoder.object','wb'))
#Deploy OHE object
pickle.dump(countryOHE,open('CountryOHE.object','wb'))

In [40]:
model.predict(np.array([[1,0,0,2345,2345,2345]]))

array([[51986.93957031]])