In [1]:
import torch

We dont need to specify requires_grad = False, since by default it flags it as False

In [2]:
tensor = torch.Tensor([[3, 4], 
                       [7, 5]])
tensor

tensor([[ 3.,  4.],
        [ 7.,  5.]])

#### The requires_grad property defines whether to track operations on this tensor
By default, it is set to False

In [3]:
tensor.requires_grad

False

#### The requires\_grad\_() function sets requires_grad to True

In [4]:
tensor.requires_grad_()

tensor([[ 3.,  4.],
        [ 7.,  5.]])

In [5]:
tensor.requires_grad

True

#### The .grad property stores all the gradients for the tensor
However, there are no gradients yet

In [6]:
print(tensor.grad)

None


#### The .grad_fn property contains the gradient function
This has not been set either

In [7]:
print(tensor.grad_fn)

None


#### Create a new output tensor from our original tensor

In [8]:
out = tensor * tensor

#### The requires_grad property has been derived from the original tensor

In [9]:
out.requires_grad

True

#### There are still no gradients

In [10]:
print(out.grad)

None


#### But there is a gradient function
This is from the multiplication operation performed on the original tensor 

In [11]:
print(out.grad_fn)

#### The original tensor still does not have a gradient function

In [12]:
print(tensor.grad_fn)

None


#### Changing the operation for the output changes the gradient function
The gradient function only contains the last operation. Here, even though there is a multiplication as well as a mean, only the mean calculation is recorded as the gradient function

In [13]:
out = (tensor * tensor).mean()
print(out.grad_fn)

#### In spite of setting a gradient function for the output, the gradients for the input tensor is still empty

In [14]:
print(tensor.grad)

None


#### To calculate the gradients, we need to explicitly perform a backward propagation

In [ ]:
out.backward()

#### The gradients are now available for the input tensor

In [16]:
print(tensor.grad)

tensor([[ 1.5000,  2.0000],
        [ 3.5000,  2.5000]])


#### The requires_grad property propagates to other tensors
Here the new_tensor is created from the original tensor and gets the original's value of requires_grad

In [17]:
new_tensor = tensor * tensor
print(new_tensor.requires_grad)

True


#### Turning off gradient calculations for tensors
You can also stops autograd from tracking history on newly created tensors with requires_grad=True by wrapping the code block in <br />
<b>with torch.no_grad():</b>

In [18]:
with torch.no_grad():
    
    new_tensor = tensor * tensor
    
    print('new_tensor = ', new_tensor)
    
    print('requires_grad for tensor = ', tensor.requires_grad)
    
    print('requires_grad for new_tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[  9.,  16.],
        [ 49.,  25.]])
requires_grad for tensor =  True
requires_grad for new_tensor =  False
