In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv('Iris.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB


In [5]:
features = data.iloc[:,1:5].values
label = data.iloc[:,5].values

In [6]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
algo = LogisticRegression()


In [7]:
# Cross Validation for Accuracy Score
# Getting an idea of what can be the best possible score I can achieve
# for the given dataset w.r.t the algo
from sklearn.model_selection import cross_val_score
cross_val_score(algo,
               features,
               label,
               cv = 10)

array([1.        , 1.        , 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.8       , 0.93333333, 1.        , 1.        ])

In [10]:
?cross_val_score

In [22]:
# Fold Validation Technique
# K-Fold Cross validation Technique
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

from sklearn.model_selection import KFold
kfold = KFold(n_splits=10,
             shuffle=True,
             random_state=1)
i = 0
for train,test in kfold.split(features):
    i = i + 1
    X_train,X_test = features[train],features[test]
    y_train,y_test= label[train],label[test]
    model.fit(X_train,y_train)
    print('Training Score is {} and Testing score is {} for Sample Split {}'
          .format(model.score(X_train,y_train),model.score(X_test,y_test),i))


Training Score is 0.9555555555555556 and Testing score is 1.0 for Sample Split 1
Training Score is 0.9629629629629629 and Testing score is 0.8 for Sample Split 2
Training Score is 0.9481481481481482 and Testing score is 1.0 for Sample Split 3
Training Score is 0.9481481481481482 and Testing score is 0.9333333333333333 for Sample Split 4
Training Score is 0.9629629629629629 and Testing score is 1.0 for Sample Split 5
Training Score is 0.9703703703703703 and Testing score is 0.9333333333333333 for Sample Split 6
Training Score is 0.9629629629629629 and Testing score is 1.0 for Sample Split 7
Training Score is 0.9703703703703703 and Testing score is 0.9333333333333333 for Sample Split 8
Training Score is 0.9555555555555556 and Testing score is 1.0 for Sample Split 9
Training Score is 0.9703703703703703 and Testing score is 0.8666666666666667 for Sample Split 10


In [14]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=10,
             shuffle=True,
             random_state=1)
i = 0
for train,test in kfold.split(features):
    i = i+1
    if i == 1:
        X_train_final,X_test_final,y_train_final,y_test_final = features[train],features[test],label[train],label[test]

In [17]:
from sklearn.linear_model import LogisticRegression
finalModel = LogisticRegression()
finalModel.fit(X_train_final,y_train_final)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
finalModel.score(X_train_final,y_train_final)

0.9555555555555556

In [19]:
finalModel.score(X_test_final,y_test_final)

1.0

In [23]:
?KFold

In [25]:
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=10,
                            test_size=0.3,
                            random_state= 1)
i = 0
for train,test in sss.split(features,label):
    i = i + 1
    X_train,X_test = features[train],features[test]
    y_train,y_test= label[train],label[test]
    model.fit(X_train,y_train)
    print('Training Score is {} and Testing score is {} for Sample Split {}'
          .format(model.score(X_train,y_train),model.score(X_test,y_test),i))

Training Score is 0.9523809523809523 and Testing score is 0.9777777777777777 for Sample Split 1
Training Score is 0.9714285714285714 and Testing score is 0.9333333333333333 for Sample Split 2
Training Score is 0.9619047619047619 and Testing score is 0.9333333333333333 for Sample Split 3
Training Score is 0.9523809523809523 and Testing score is 0.9555555555555556 for Sample Split 4
Training Score is 0.9523809523809523 and Testing score is 0.9777777777777777 for Sample Split 5
Training Score is 0.9523809523809523 and Testing score is 0.9777777777777777 for Sample Split 6
Training Score is 0.9619047619047619 and Testing score is 0.9777777777777777 for Sample Split 7
Training Score is 0.9523809523809523 and Testing score is 0.9777777777777777 for Sample Split 8
Training Score is 0.9619047619047619 and Testing score is 0.9333333333333333 for Sample Split 9
Training Score is 0.9714285714285714 and Testing score is 0.8888888888888888 for Sample Split 10


In [40]:
# RFE can be applied for the below following:
# Based on Co-effient values --- Regression (LinearRegression, SVR, DecisionTreeRegressor, RForestR)
# Based on feature_importance --- Classification (DecisionTreeClassifier & RandomForestClassifier)
from sklearn.tree import DecisionTreeClassifier
algo = DecisionTreeClassifier()
from sklearn.ensemble import RandomForestClassifier
algo2 = RandomForestClassifier()
from sklearn.feature_selection import RFE
selectFeatures = RFE(estimator=algo2,
                    step= 1) #It will remove one feature at each iteration
selectFeatures.fit(features,label)
print(selectFeatures.support_)
print(data.columns[1:5])
print(selectFeatures.ranking_)

[False False  True  True]
Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')
[2 3 1 1]


In [42]:
# RFE ---> StratifiedShuffleSplit ---> model with good split

finalFeatures = features[:,2:4]
#print(finalFeatures)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(finalFeatures,
                                                label,
                                                test_size=0.2,
                                                random_state=10)
algo.fit(X_train,y_train)
print(algo.score(X_train,y_train))
print(algo.score(X_test,y_test))


0.9916666666666667
0.9666666666666667


In [47]:
#Example of Feature Importance
#Applicable only for DecisionTreeClassifier and RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=10)
algo = DecisionTreeClassifier()
algo.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [48]:
algo.feature_importances_

array([0.01669798, 0.02540478, 0.90945348, 0.04844377])