In [1]:
import torch

In [2]:
tensor= torch.Tensor([[3,4],[7,5]])
tensor

tensor([[3., 4.],
        [7., 5.]])

In [4]:
tensor.requires_grad

False

In [5]:
tensor.requires_grad_()

tensor([[3., 4.],
        [7., 5.]], requires_grad=True)

In [6]:
tensor.requires_grad

True

In [7]:
print(tensor.grad)

None


In [8]:
print(tensor.grad_fn)

None


In [9]:
out=tensor*tensor

In [11]:
out.requires_grad

True

In [14]:
print(out.grad)

None


<ipython-input-14-b5f72fce5729>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:485.)
  print(out.grad)


In [13]:
print(out.grad_fn)

In [15]:
out=(tensor*tensor).mean()
print(out.grad_fn)

In [16]:
out.backward()

In [18]:
print(tensor.grad)

tensor([[1.5000, 2.0000],
        [3.5000, 2.5000]])


In [20]:
with torch.no_grad():
    new_tensor=tensor*tensor
    
    print('new_tensor=',new_tensor)
    
    print('requires_grad for tensor=',tensor.requires_grad)
    
    print('requires_grad for new_tensor=',new_tensor.requires_grad)
    
    

new_tensor= tensor([[ 9., 16.],
        [49., 25.]])
requires_grad for tensor= True
requires_grad for new_tensor= False
