In [1]:
import numpy as np

In [14]:
from tabulate import tabulate
def DisplayMatrix(M):
    print(tabulate(M, headers='keys', tablefmt='double_grid'))

In [2]:
myList = [1,2,3]
type(myList)

list

In [3]:
#we could do is cast list as an array
myarray=np.array(myList)
type(myarray)

numpy.ndarray

In [19]:
'''
Basically it returns evenly spaced values within a given interval, so you give it a start and a stop
and an optional step size.
'''
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
'''
Now often what we're going to be doing is creating a two dimensional or three dimensional array, all
of one single value.

Now you'll notice each of these zeros has a little decimal point after it.
That's because by default, numpy is going to automatically create floats instead of just pure integers.
'''
DisplayMatrix(np.zeros(shape=(5,5)))

╔═══╦═══╦═══╦═══╦═══╗
║ 0 ║ 0 ║ 0 ║ 0 ║ 0 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 0 ║ 0 ║ 0 ║ 0 ║ 0 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 0 ║ 0 ║ 0 ║ 0 ║ 0 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 0 ║ 0 ║ 0 ║ 0 ║ 0 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 0 ║ 0 ║ 0 ║ 0 ║ 0 ║
╚═══╩═══╩═══╩═══╩═══╝


In [6]:
type(0.)

float

In [23]:
'''
The other one we're going to be using often is empty ones and it's going to be the same thing it takes
in a shape argument.

NP Zeros, which creates an array of zeros for us and NP one which creates an array of ones for us
where this first value in the shape is how many rows you have or the height of the array.
And the second one is how many columns you have or the width of the array.
'''
DisplayMatrix(np.ones(shape=(5,5)))

╔═══╦═══╦═══╦═══╦═══╗
║ 1 ║ 1 ║ 1 ║ 1 ║ 1 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 1 ║ 1 ║ 1 ║ 1 ║ 1 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 1 ║ 1 ║ 1 ║ 1 ║ 1 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 1 ║ 1 ║ 1 ║ 1 ║ 1 ║
╠═══╬═══╬═══╬═══╬═══╣
║ 1 ║ 1 ║ 1 ║ 1 ║ 1 ║
╚═══╩═══╩═══╩═══╩═══╝


In [11]:
'''
What this does is it allows me to create the same random numbers each time.

So that means I'm going to say here.
Grabbed me from 0 to 100.Give me 10 random numbers.

Notice how my seed and the creation of this array are actually happening in the same cell.
The reason I have 101 here is just a seed number.
The actual value is pretty arbitrary, but I want you to use the same number I do.
That way, when you actually create these random values, you get the same random numbers.


'''
np.random.seed(101)
arr=np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [24]:
'''
So if you ever want to find out the max value of an array
'''
arr.max()

95

In [25]:
'''
If I wanted to figure out the location of that max value
'''
arr.argmax()

0

In [26]:
'''
So if you ever want to find out the min value of an array
'''
arr.min()

9

In [27]:
'''
If I wanted to figure out the location of that min value
'''
arr.argmin()

7

In [28]:
'''
And finally, if you want to figure out the average value or the mean, you can just call our mean.
'''
arr.mean()

60.8

In [29]:
'''
So if I check out the shape parameter, notice how I'm just calling shape with no parentheses here it
returns back a shape 10 comma and then nothing because it's actually just a single vector.
'''
arr.shape

(10,)

In [31]:
'''
What I could do is say reshape this to another set of dimensions.

because if you have an array of 2 by 10, that means there's 2 * 10 times ten elements.
That means 20 elements.
'''
DisplayMatrix(arr.reshape(2,5))

╔════╦════╦════╦════╦════╗
║ 95 ║ 11 ║ 81 ║ 70 ║ 63 ║
╠════╬════╬════╬════╬════╣
║ 87 ║ 75 ║  9 ║ 77 ║ 40 ║
╚════╩════╩════╩════╩════╝


In [32]:
DisplayMatrix(arr.reshape(5,2))

╔════╦════╗
║ 95 ║ 11 ║
╠════╬════╣
║ 81 ║ 70 ║
╠════╬════╣
║ 63 ║ 87 ║
╠════╬════╣
║ 75 ║  9 ║
╠════╬════╣
║ 77 ║ 40 ║
╚════╩════╝


In [34]:
'''
Create and 1D Array and Reshape it 2D array for 10 by 10 matrix
'''
mat = np.arange(0,100).reshape(10,10)
DisplayMatrix(mat)

╔════╦════╦════╦════╦════╦════╦════╦════╦════╦════╗
║  0 ║  1 ║  2 ║  3 ║  4 ║  5 ║  6 ║  7 ║  8 ║  9 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 10 ║ 11 ║ 12 ║ 13 ║ 14 ║ 15 ║ 16 ║ 17 ║ 18 ║ 19 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 20 ║ 21 ║ 22 ║ 23 ║ 24 ║ 25 ║ 26 ║ 27 ║ 28 ║ 29 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 30 ║ 31 ║ 32 ║ 33 ║ 34 ║ 35 ║ 36 ║ 37 ║ 38 ║ 39 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 40 ║ 41 ║ 42 ║ 43 ║ 44 ║ 45 ║ 46 ║ 47 ║ 48 ║ 49 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 50 ║ 51 ║ 52 ║ 53 ║ 54 ║ 55 ║ 56 ║ 57 ║ 58 ║ 59 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 60 ║ 61 ║ 62 ║ 63 ║ 64 ║ 65 ║ 66 ║ 67 ║ 68 ║ 69 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 70 ║ 71 ║ 72 ║ 73 ║ 74 ║ 75 ║ 76 ║ 77 ║ 78 ║ 79 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 80 ║ 81 ║ 82 ║ 83 ║ 84 ║ 85 ║ 86 ║ 87 ║ 88 ║ 89 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 90 ║ 91 ║ 

In [35]:
mat.shape

(10, 10)

In [36]:
'''
So let's imagine that I wanted to grab a single digit from this array.
What I do is I use indexing.

So let's say I want the value at row index zero where column is index one.
'''
row=0
col=1
mat[row,col]

1

In [37]:
'''
Now let's imagine you wanted to grab all the items in a row or all the items in a column.
You do that with slicing.

So what that returns back is every single value for every single row in the column.One.
so that returns back an entire column.

'''
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [38]:
mat[:,1].shape

(10,)

In [39]:
DisplayMatrix(mat[:,1].reshape(10,1))

╔════╗
║  1 ║
╠════╣
║ 11 ║
╠════╣
║ 21 ║
╠════╣
║ 31 ║
╠════╣
║ 41 ║
╠════╣
║ 51 ║
╠════╣
║ 61 ║
╠════╣
║ 71 ║
╠════╣
║ 81 ║
╠════╣
║ 91 ║
╚════╝


In [43]:
'''
Gives the First Row -> mat[0,:]
'''
DisplayMatrix(mat[:,1].reshape(1,10))

╔═══╦════╦════╦════╦════╦════╦════╦════╦════╦════╗
║ 1 ║ 11 ║ 21 ║ 31 ║ 41 ║ 51 ║ 61 ║ 71 ║ 81 ║ 91 ║
╚═══╩════╩════╩════╩════╩════╩════╩════╩════╩════╝


In [44]:
'''
So let's imagine I wanted to grab this first 3 by 3 of Matrix.

What I could do is say starting at index zero, colon three.
For those rows and then for the columns do the same thing.
Zero Colon three.

And what that does is it says, okay, grab all the rows starting at zero up to not including three.then grab all those columns
'''
DisplayMatrix(mat[0:3,0:3])

╔════╦════╦════╗
║  0 ║  1 ║  2 ║
╠════╬════╬════╣
║ 10 ║ 11 ║ 12 ║
╠════╬════╬════╣
║ 20 ║ 21 ║ 22 ║
╚════╩════╩════╝


In [45]:
'''
So the last thing I want to show you is if you want to actually reassign these numbers to a different
value, you could say equals zero.
'''

mat[0:3,0:3]=0
DisplayMatrix(mat)

╔════╦════╦════╦════╦════╦════╦════╦════╦════╦════╗
║  0 ║  0 ║  0 ║  3 ║  4 ║  5 ║  6 ║  7 ║  8 ║  9 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║  0 ║  0 ║  0 ║ 13 ║ 14 ║ 15 ║ 16 ║ 17 ║ 18 ║ 19 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║  0 ║  0 ║  0 ║ 23 ║ 24 ║ 25 ║ 26 ║ 27 ║ 28 ║ 29 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 30 ║ 31 ║ 32 ║ 33 ║ 34 ║ 35 ║ 36 ║ 37 ║ 38 ║ 39 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 40 ║ 41 ║ 42 ║ 43 ║ 44 ║ 45 ║ 46 ║ 47 ║ 48 ║ 49 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 50 ║ 51 ║ 52 ║ 53 ║ 54 ║ 55 ║ 56 ║ 57 ║ 58 ║ 59 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 60 ║ 61 ║ 62 ║ 63 ║ 64 ║ 65 ║ 66 ║ 67 ║ 68 ║ 69 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 70 ║ 71 ║ 72 ║ 73 ║ 74 ║ 75 ║ 76 ║ 77 ║ 78 ║ 79 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 80 ║ 81 ║ 82 ║ 83 ║ 84 ║ 85 ║ 86 ║ 87 ║ 88 ║ 89 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 90 ║ 91 ║ 

In [47]:
'''
If you want to actually affect a kind of copy of The Matrix, 
'''

newMat=mat.copy()
DisplayMatrix(newMat)

╔════╦════╦════╦════╦════╦════╦════╦════╦════╦════╗
║  0 ║  0 ║  0 ║  3 ║  4 ║  5 ║  6 ║  7 ║  8 ║  9 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║  0 ║  0 ║  0 ║ 13 ║ 14 ║ 15 ║ 16 ║ 17 ║ 18 ║ 19 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║  0 ║  0 ║  0 ║ 23 ║ 24 ║ 25 ║ 26 ║ 27 ║ 28 ║ 29 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 30 ║ 31 ║ 32 ║ 33 ║ 34 ║ 35 ║ 36 ║ 37 ║ 38 ║ 39 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 40 ║ 41 ║ 42 ║ 43 ║ 44 ║ 45 ║ 46 ║ 47 ║ 48 ║ 49 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 50 ║ 51 ║ 52 ║ 53 ║ 54 ║ 55 ║ 56 ║ 57 ║ 58 ║ 59 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 60 ║ 61 ║ 62 ║ 63 ║ 64 ║ 65 ║ 66 ║ 67 ║ 68 ║ 69 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 70 ║ 71 ║ 72 ║ 73 ║ 74 ║ 75 ║ 76 ║ 77 ║ 78 ║ 79 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 80 ║ 81 ║ 82 ║ 83 ║ 84 ║ 85 ║ 86 ║ 87 ║ 88 ║ 89 ║
╠════╬════╬════╬════╬════╬════╬════╬════╬════╬════╣
║ 90 ║ 91 ║ 