In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
startupData = pd.read_csv('50_Startups.csv')

In [3]:
startupData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     50 non-null float64
Marketing Spend    50 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB


In [8]:
finalDF = pd.concat([ pd.get_dummies(startupData.State), startupData.iloc[:,[0,1,2,4]] ] , axis= 1 )
finalDF

California  Florida  New York  R&D Spend  Administration  Marketing Spend  \
0            0        0         1  165349.20       136897.80        471784.10   
1            1        0         0  162597.70       151377.59        443898.53   
2            0        1         0  153441.51       101145.55        407934.54   
3            0        0         1  144372.41       118671.85        383199.62   
4            0        1         0  142107.34        91391.77        366168.42   
5            0        0         1  131876.90        99814.71        362861.36   
6            1        0         0  134615.46       147198.87        127716.82   
7            0        1         0  130298.13       145530.06        323876.68   
8            0        0         1  120542.52       148718.95        311613.29   
9            1        0         0  123334.88       108679.17        304981.62   
10           0        1         0  101913.08       110594.11        229160.95   
11           1        0         0  100671.96        91790.61        249744.55   
12           0        1         0   93863.75       127320.38        249839.44   
13           1        0         0   91992.39       135495.07        252664.93   
14           0        1         0  119943.24       156547.42        256512.92   
15           0        0         1  114523.61       122616.84        261776.23   
16           1        0         0   78013.11       121597.55        264346.06   
17           0        0         1   94657.16       145077.58        282574.31   
18           0        1         0   91749.16       114175.79        294919.57   
19           0        0         1   86419.70       153514.11             0.00   
20           1        0         0   76253.86       113867.30        298664.47   
21           0        0         1   78389.47       153773.43        299737.29   
22           0        1         0   73994.56       122782.75        303319.26   
23           0        1         0   67532.53       105751.03        304768.73   
24           0        0         1   77044.01        99281.34        140574.81   
25           1        0         0   64664.71       139553.16        137962.62   
26           0        1         0   75328.87       144135.98        134050.07   
27           0        0         1   72107.60       127864.55        353183.81   
28           0        1         0   66051.52       182645.56        118148.20   
29           0        0         1   65605.48       153032.06        107138.38   
30           0        1         0   61994.48       115641.28         91131.24   
31           0        0         1   61136.38       152701.92         88218.23   
32           1        0         0   63408.86       129219.61         46085.25   
33           0        1         0   55493.95       103057.49        214634.81   
34           1        0         0   46426.07       157693.92        210797.67   
35           0        0         1   46014.02        85047.44        205517.64   
36           0        1         0   28663.76       127056.21        201126.82   
37           1        0         0   44069.95        51283.14        197029.42   
38           0        0         1   20229.59        65947.93        185265.10   
39           1        0         0   38558.51        82982.09        174999.30   
40           1        0         0   28754.33       118546.05        172795.67   
41           0        1         0   27892.92        84710.77        164470.71   
42           1        0         0   23640.93        96189.63        148001.11   
43           0        0         1   15505.73       127382.30         35534.17   
44           1        0         0   22177.74       154806.14         28334.72   
45           0        0         1    1000.23       124153.04          1903.93   
46           0        1         0    1315.46       115816.21        297114.46   
47           1        0         0       0.00       135426.92             0.00   
48           0        0         1  

In [10]:
list1 = list(startupData.State.unique())
list1

['New York', 'California', 'Florida']

In [11]:
np.zeros(len(list1))

array([0., 0., 0.])

In [12]:
#Create a function that can handle DummyVariables
def getDummyVariables(uniqueList, categorical_value):
    listToCheck = sorted(uniqueList)
    resultVariable = np.zeros(len(listToCheck))
    counter = 0
    
    for i in range(0, len(listToCheck)):
        if listToCheck[i] == categorical_value:
            resultVariable[counter] = 1
        else:
            counter += 1
    
    return resultVariable
    

In [15]:
getDummyVariables(list1,'New York')

array([0., 0., 1.])

In [16]:
#Example
rdSpend= float(input("Enter R&D Spend: "))
admSpend = float(input("Enter Admin Spend: "))
markSpend = float(input("Enter Marketing Spend: "))
state = input("Enter State: ")

if state in list1:
    dummyVariables = getDummyVariables(list1,state)
    features = np.append(dummyVariables, np.array([[rdSpend,admSpend,markSpend]]))
    print(features)



Enter R&D Spend: 2345
Enter Admin Spend: 234
Enter Marketing Spend: 2345
Enter State: California
[1.000e+00 0.000e+00 0.000e+00 2.345e+03 2.340e+02 2.345e+03]
