In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    9 non-null      object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [2]:
#Load the data
data = pd.read_csv('pre-process_datasample.csv')

In [3]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [92]:
fetures = data.iloc[:,[0,1,2]].values
label = data.iloc[:,3].values

In [93]:
fetures

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       [nan, 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [94]:
from sklearn.impute import SimpleImputer

In [95]:
ageImputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [96]:
fetures[:,[1]]

array([[44.0],
       [27.0],
       [30.0],
       [38.0],
       [40.0],
       [35.0],
       [nan],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [97]:
fetures[:,[1]]=ageImputer.fit_transform(fetures[:,[1]])
fetures[:,[1]]

array([[44.0],
       [27.0],
       [30.0],
       [38.0],
       [40.0],
       [35.0],
       [38.77777777777778],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [98]:
from sklearn.impute import SimpleImputer
salaryImputer = Imputer(missing_values='NaN',strategy='mean',axis=0)

In [99]:
fetures[:,[2]] =salaryImputer.fit_transform(fetures[:,[2]])
fetures[:,[2]]

array([[72000.0],
       [48000.0],
       [54000.0],
       [61000.0],
       [63777.77777777778],
       [58000.0],
       [52000.0],
       [79000.0],
       [83000.0],
       [67000.0]], dtype=object)

In [100]:
from sklearn.impute import SimpleImputer
countryImputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
fetures[:,[0]]=countryImputer.fit_transform(fetures[:,[0]])
fetures[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'France', 'France'], dtype=object)

In [101]:
from sklearn.preprocessing import LabelEncoder
countryEncoder=LabelEncoder()
fetures[:,0]=countryEncoder.fit_transform(fetures[:,0])
fetures[:,0]
fetures

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [0, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [104]:
from sklearn.preprocessing import OneHotEncoder
countryOHE=OneHotEncoder(categorical_features=[0])
fetures =countryOHE.fit_transform(fetures).toarray()
fetures

/Users/subhasishbiswas/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.40000000e+01, 7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        3.00000000e+01, 5.40000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.50000000e+01, 5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.80000000e+01, 7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.00000000e+01, 