In [1]:
import numpy as np

In [2]:
sampleArray = np.arange(0,11)

In [3]:
sampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Extract 7
sampleArray[7]

7

In [5]:
#Extract series
sampleArray[2:6]

array([2, 3, 4, 5])

In [6]:
twodimExample = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
twodimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
            #row col
twodimExample[1][1]

5

In [9]:
twodimExample[2][0]

7

In [12]:
#Extract the first row
twodimExample[0]

array([1, 2, 3])

In [13]:
twodimExample[0][0:2]

array([1, 2])

In [16]:
twodimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#Another way to get subset/slice of ndarray using series
twodimExample[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [22]:
#Fancy Indexing
#5--> 1,1
#6--> 1,2
#8--> 2,1
#9--> 2,2
twodimExample[[1,1,2,2],[1,2,1,2]].reshape(2,2)

array([[5, 6],
       [8, 9]])

In [23]:
twodimExample[[0,0,2,2],[0,2,0,2]].reshape(2,2)

array([[1, 3],
       [7, 9]])

In [25]:
twodimExample[[0,1,2,2],[0,1,1,2]].reshape(2,2)

array([[1, 5],
       [8, 9]])

In [26]:
# Use Comparison Operators
sampleArray = np.arange(0,11)
sampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
sampleArray % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [28]:
sampleArray[sampleArray % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [29]:
sampleArray[sampleArray > 6]

array([ 7,  8,  9, 10])

In [32]:
sampleArray[(sampleArray > 6) & (sampleArray <= 9)] 

array([7, 8, 9])

In [33]:
sampleArray[(sampleArray > 6) | (sampleArray <= 9)] 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#and ----> &
#or -----> |
#not ----> !

In [34]:
#Broadcasting
array1 = np.arange(0,11)

In [35]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
array1[0:5] = 99 #Broadcasting

In [37]:
array1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [38]:
list1 = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]

In [40]:
list1[0:5] = 99

TypeError: can only assign an iterable

In [41]:
#Slice of Array
arraySliceDemo = np.arange(0,11)

In [42]:
arraySliceDemo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arraySubset = arraySliceDemo[0:5]
arraySubset

array([0, 1, 2, 3, 4])

In [44]:
arraySubset = arraySubset * 2
arraySubset

array([0, 2, 4, 6, 8])

In [64]:
arraySubset * 10

array([ 0, 20, 40, 60, 80])

In [66]:
arraySliceDemo

array([ 0,  2,  4,  6,  8,  5,  6,  7,  8,  9, 10])

In [65]:
arraySliceDemo

array([ 0,  2,  4,  6,  8,  5,  6,  7,  8,  9, 10])

In [48]:
arraySubset

array([0, 2, 4, 6, 8])

In [50]:
arraySliceDemo[0:5] = arraySubset

In [51]:
arraySliceDemo

array([ 0,  2,  4,  6,  8,  5,  6,  7,  8,  9, 10])

In [52]:
#Slice of Array
arraySliceDemo1 = np.arange(0,11)

In [53]:
arraySliceDemo1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
s1 = arraySliceDemo1[0:5]
s1 #POinter location

array([0, 1, 2, 3, 4])

In [55]:
s1[:]= 6

In [56]:
s1

array([6, 6, 6, 6, 6])

In [57]:
arraySliceDemo1

array([ 6,  6,  6,  6,  6,  5,  6,  7,  8,  9, 10])

In [58]:
arraySliceDemo1

array([ 6,  6,  6,  6,  6,  5,  6,  7,  8,  9, 10])

In [59]:
subsetExample = arraySliceDemo1[0:5].copy()

In [60]:
subsetExample[:]=99

In [61]:
subsetExample

array([99, 99, 99, 99, 99])

In [62]:
arraySliceDemo1

array([ 6,  6,  6,  6,  6,  5,  6,  7,  8,  9, 10])

# Operations

In [67]:
array1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [68]:
np.sqrt(array1)

array([9.94987437, 9.94987437, 9.94987437, 9.94987437, 9.94987437,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [69]:
np.exp(array1)

array([9.88903032e+42, 9.88903032e+42, 9.88903032e+42, 9.88903032e+42,
       9.88903032e+42, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [70]:
np.max(array1)

99

In [71]:
np.min(array1)

5

In [72]:
np.sin(array1)

array([-0.99920683, -0.99920683, -0.99920683, -0.99920683, -0.99920683,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [73]:
np.log(array1)

array([4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])