In [3]:
import numpy as np

In [4]:
list=[1,2,3,4]

arr = np.array(list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
#2d Array
matrix=[[1,2,3],[4,5,6],[7,8,9]]

matrixArr=np.array(matrix)

In [7]:
matrixArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#arrange function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
#zeros 
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#Ones Array
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#linspace -> Evely spaced Array

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:

np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
#Identity Matrix ->2d Squre Matrix with diagonal 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#random number

np.random.rand(10)

array([0.6239849 , 0.35723437, 0.83920093, 0.20928973, 0.71790484,
       0.27246381, 0.33680435, 0.18738299, 0.08183498, 0.64490202])

In [18]:
# random number standard normal distribution

np.random.randn(10)

array([ 0.16032671, -0.22532846, -0.64638299, -1.87301644,  1.93235062,
        1.05814375,  0.21861794,  0.6015207 ,  0.16099072, -0.62338939])

In [19]:
np.random.randn(5,5)

array([[-9.46838920e-01, -4.68186087e-01, -4.11518949e-01,
         9.63773091e-01, -2.53593743e-03],
       [ 1.25819389e+00,  9.92412329e-01,  2.62175081e-01,
         1.77914738e+00, -2.75469287e+00],
       [ 9.80411997e-01,  2.48865532e-01,  3.36037941e-01,
         1.56409401e-01, -9.85064711e-01],
       [-1.30066200e+00,  1.03300901e-01, -1.56960450e+00,
         1.53650354e+00, -6.46790201e-01],
       [-1.06812442e+00,  1.25943548e+00, -7.66254754e-02,
        -2.08692584e-01, -6.84295451e-01]])

In [20]:
# 5 random integer between 1->100
np.random.randint(1,100,5)

array([74, 74, 18, 76, 68])

In [21]:
#creating random matrixx

randarr = np.random.randint(1,100,25)
randarr

array([31, 75, 89, 11, 80, 52, 61, 21,  7, 60, 35, 48, 84, 15, 30, 61, 88,
       29, 77, 79,  9, 32, 72, 16, 56])

In [22]:
randarr.reshape(5,5)

array([[31, 75, 89, 11, 80],
       [52, 61, 21,  7, 60],
       [35, 48, 84, 15, 30],
       [61, 88, 29, 77, 79],
       [ 9, 32, 72, 16, 56]])

In [23]:
#max value
randarr.max()

89

In [24]:
randarr.min()

7

In [25]:
#Index Location of Maximun value
randarr.argmax()

2

In [26]:
from numpy.random import randint

In [27]:
randint(2,10)

4

In [28]:
#slicing

arr =np.arange(0,11)

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
#Everything till index 5
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [31]:
#everyting till index 6 to last
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[1,2]

6

In [34]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [35]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
boolArray=arr>5
boolArray

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
arr[boolArray]

array([ 6,  7,  8,  9, 10])

In [39]:
#
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [40]:
arr[arr<5]

array([1, 2, 3, 4])

In [41]:
#2d random Array
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr+arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [45]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [47]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [48]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [49]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [50]:
np.max(arr)

10

In [51]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [52]:
np.log(arr)

<ipython-input-52-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [53]:
matrix2d=np.linspace(1,25,25).reshape(5,5)

In [54]:
matrix2d.sum()

325.0

In [55]:
matrix2d.std()

7.211102550927978

In [57]:
#get sum of the column
matrix2d.sum(axis=0)

array([55., 60., 65., 70., 75.])